name: Java Selenium CI with Docker and GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      # Docker image build
      - name: Build Docker Image
        run: docker build -t selenium-tests .

      # Run Tests in Docker
      - name: Run Tests in Docker
        run: docker run --name selenium-tests-container selenium-tests

      # Copy Extent Reports from Docker
      - name: Copy Extent Reports from Docker
        run: docker cp selenium-tests-container:/app/test-output ./test-output

      # Archive Extent Report
      - name: Archive Extent Report
        uses: actions/upload-artifact@v3
        with:
          name: extent-report
          path: test-output/

  deploy-report:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      # Download Extent Report artifact
      - name: Download Extent Report artifact
        uses: actions/download-artifact@v3
        with:
          name: extent-report
          path: ./report

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./report
